spring:
  profiles:
    active: usage_message
  rabbitmq:
    host: ${HOST:10.0.0.10}
    #rabbitmqcluster.default.svc.cluster.local
    port: ${PORT:5672}
    username: ${USER:admin}
    password: ${PASS:securepassword}
shovel:
  exchange: ${SHOVEL:cloud_shovel_exchange}
logging:
  level:
    org: ERROR
tutorial:
  client:
    duration: 10000
