spring:
  rabbitmq:
    host: ${HOST:10.0.0.6}
    #rabbitmqcluster.default.svc.cluster.local
    port: ${PORT:31812}
    username: ${USER:guest}
    password: ${PASS:guest}
shovel:
  exchange: ${SHOVEL:shovel_exchange}
